services:
  tanuki-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=tanuki-db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d tanuki-db" ]
      interval: 10s
      timeout: 5s
      retries: 5