spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS auth_schema;
  jpa:
    properties:
      hibernate:
        default_schema: auth_schema
        dialect: org.hibernate.dialect.CockroachDialect
        jdbc:
          lob:
            non_contextual_creation: true

jwt:
  secret: ${JWT_SECRET:mySecretToChange@123}
  expiration: ${JWT_EXPIRATION:300000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:172800000}