spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tanuki-db
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: auth_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: test-secret-key-that-needs-to-be-long-enough-to-be-secure-32-chars
  expiration: 900000
  refresh-expiration: 604800000
