spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tanuki-db
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: auth_schema

jwt:
  secret: test-secret-key-that-needs-to-be-long-enough-to-be-secure-32-chars
  expiration: 86400000