spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS auth_schema;
  jpa:
    properties:
      hibernate:
        default_schema: auth_schema
        dialect: org.hibernate.dialect.CockroachDialect
        jdbc:
          lob:
            non_contextual_creation: true

jwt:
  secret: ${JWT_SECRET:devSecretKeyForProjectTanukiMustBeAtLeast32BytesLong}
  expiration: ${JWT_EXPIRATION:300000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:172800000}

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:https://dev.project-tanuki.net}
  google:
    client-id: 1091577412614-qarcph78k6jkq18jgecrlsl582pugrau.apps.googleusercontent.com
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}

logging:
  level:
    io.github.peterberghuis: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE