spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1091577412614-3fr0ubc3mllrfr9jc2gt0m8rue2e8n5m.apps.googleusercontent.com
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS auth_schema;
  jpa:
    properties:
      hibernate:
        default_schema: auth_schema
        dialect: org.hibernate.dialect.CockroachDialect
        jdbc:
          lob:
            non_contextual_creation: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:900000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:https://project-tanuki.net}
  frontend-url: ${FRONTEND_URL:https://project-tanuki.net}
