spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tanuki-db
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS profile_schema;
  jpa:
    properties:
      hibernate:
        default_schema: profile_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect
